version: "3.8"

services:
  # SERVICE 1: DATABASE (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: algominds_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: algominds
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - algominds-net

  # SERVICE 3: CODE EXECUTION SANDBOX (Piston)
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: algominds_piston
    ports:
      - "2000:2000"
    networks:
      - algominds-net
    tty: true
    stdin_open: true
    restart: unless-stopped
    privileged: true # QUAN TRỌNG: Cấp quyền để Piston tạo môi trường isolate
    volumes:
      - piston_data:/piston

  # SERVICE 2: CACHE & QUEUE (Redis)
  redis:
    image: redis:7-alpine
    container_name: algominds_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - algominds-net

volumes:
  postgres_data:
  redis_data:
  piston_data:

networks:
  algominds-net:
